apiVersion: v1
kind: Service

metadata:
  name: ai-knowledge-ui-service

spec:
  selector:
    app: ai-knowledge-ui

  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501

  type: ClusterIP